server:
 port: 8071

spring:
  application:
    name: FM_admin

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fillme_a
    username: root
    password: inno
#    url: jdbc:mysql://141.164.45.147:3306/fillme_dev
#    username: root
#    password: noname123
    hikari:
      auto-commit: true
      minimum-idle: 10
      maximum-pool-size: 150
      idle-timeout: 60000
      max-lifetime: 200000
      connection-timeout: 20000
      pool-name: '[ CONNECT-DB ] ===>'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  security:
    access-token: 9QZaVt1gRjmNWtEPksgNaJ7OT6OmnbNQxxx334sdeaFxxx1
    access-token-time: 18000000 # 5 hours
    refresh-token: 9QZaVt1gRjmNWtEPksgNaJ7OT6OmnbNQxxx334sdeaFxxx2
    refresh-token-time: 15552000000 # 6 months

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

springdoc:
  api-docs:
    url-uat: http://localhost:8071
    url-dev: http://141.164.45.147:8080

cors:
  allowed:
    origins: "*"
    methods: "GET,POST,PUT,DELETE"
    headers: "Content-Type,Authorization"
  permit-all:
    endpoint:
      /swagger-ui/**,
      /v3/api-docs/**,
      /swagger-resources/**,
      /webjars/**,
      /api/auth/**,
      /api/policy/**,
      /web/auth/**,
      /css/**,
      /image/**,
      /script/**,
      /web/**
      
      

logging:
  level:
    org.springframework.security: DEBUG

#  http://localhost:8080/oauth2/authorization/facebook
#  http://localhost:8080/oauth2/authorization/kakao
#  http://localhost:8080/oauth2/authorization/naver